### ISSUE TITLE
To-do list for PR into master

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/designs#16]
- [x] Go through and document all user-functions 
- [x] Ensure all functions are tested (check coverage)
- [x] Documentation for DesignLibrary package itself 
- [x] Add internal checks to all functions 
- [x] Test that all the RDS stuff works, and has big sims 
- [x] Check all vignettes compiling nicely
