### ISSUE TITLE
Designs todo

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/designs#3]
* Observational designs for descriptive inference
  - [ ] Simple random sampling
  - [ ] Stratified clustered random sampling
  - [ ] Measuring latent variables
  - [ ] Topic analysis
  - [ ] Respondent driven sampling
  - [ ] Multilevel regression and poststratification
  
* Experimental designs for descriptive inference
  - [ ] Audit experiments
  - [ ] List experiments
  - [ ] Randomized response
  - [ ] Conjoint experiments
  - [ ] Experimental games
  
* Experimental designs for causal inference
  - [ ] Multiarm designs
  - [ ] Experiments with blocks and clusters
  - [ ] Factorial designs
  - [ ] Encouragement designs 
  - [ ] Stepped wedge designs   
  - [ ] Crossover designs
  - [ ] Parallel design for mediation effects
  - [ ] Partial population design for spillover analysis
  - [ ] Selective trials
  - [ ] Adaptive trials 

* Observational designs for causal inference
  - [ ] Difference in differences
  - [ ] Matching
  - [ ] Regression discontinuity designs
  - [ ] Synthetic control
  - [ ] Process tracing
  - [ ] Cross national time series
